version: '3.8'
services:
    dynamodb-local:
        command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
        image: 'amazon/dynamodb-local:latest'
        container_name: dynamodb-local
        ports:
            # We listen on 8001 outside to avoid conflicts with jest-dynamodb
            # in case we want to run tests while having the environment running
            # locallly
            - '8001:8000'
        volumes:
            - './docker/dynamodb:/home/dynamodblocal/data'
        working_dir: /home/dynamodblocal
